### ISSUE TITLE
gdistance:geoCorretion with type "c" or type "r"? 

### ISSUE THREAD

**Issue by capsizingHR** [ISAAKiel/pathAAR#5]
In the function "theoPath_herzog" the function gdistance::geoCorrection with type "r" is used for the geographic correction of the previously created TransitionLayer.
` slope <- gdistance::geoCorrection(tran_hdiff, type="r", scl=TRUE)`

Why "r"a and not "c"? In the vignette of the gdistance package it seems that method "r" is only used for totally randomised walks (or really, really low values theta, that approach zero). 
Edit: As also stated in the vignette, there is as of now no analytical method to decide which method to use and:

> Users who want to work with intermediate values of theta are encouraged to
experiment with different solutions.

So maybe the method should not be hardcoded?

**Comment by FFaupel** [comment]
As I used an existing research project, I may have chosen "r" after experimenting. Anyway, our users should have the chance to set this themselves. But, lets set "c" as default. This is probably the most frequent scenario, or?

**Comment by capsizingHR** [comment]
Ah, ok, that explains it, I think ;) 
Ok, than I will change the functions to incorporate a default "c" and the possibility to change it!
And yes, if I understand the vignette for gdistance correctly, it will be mostly method "c" that is useful, as long as the user is not looking for a (near) totally randomised walk

**Comment by capsizingHR** [comment]
Implemented
